export const PASS_STATE = Object.freeze({
  PROPOSED: "PROPOSED",
  ADMITTED: "ADMITTED",
  PLANNED: "PLANNED",
  RESERVED: "RESERVED",
  DISPATCHED: "DISPATCHED",
  RECEIVED: "RECEIVED",
  VERIFIED: "VERIFIED",
  SETTLED: "SETTLED",
  REJECTED: "REJECTED",
  FAILED: "FAILED",
  RELEASED: "RELEASED"
});

export const EFFECT_CLASS = Object.freeze({
  PURE: "PURE",
  READ: "READ",
  PROPOSE: "PROPOSE",
  MUTATE: "MUTATE",
  IRREVERSIBLE: "IRREVERSIBLE"
});

export const RISK_CLASS = Object.freeze({
  TRIVIAL: "TRIVIAL",
  NORMAL: "NORMAL",
  IMPORTANT: "IMPORTANT",
  HIGH: "HIGH",
  CRITICAL: "CRITICAL"
});
