export const CONSTITUTION_VERSION = "0.1.0";

export const CONSTITUTION = Object.freeze([
  "NO_SILENT_OVERSPEND",
  "NO_HIDDEN_QUALITY_FLOOR_VIOLATION",
  "NO_AUTHORITY_EXPANSION",
  "NO_EVIDENCE_FLOOR_VIOLATION",
  "NO_INCOMPATIBLE_SEMANTIC_REUSE",
  "NO_CACHE_SUBSTITUTION_FOR_SIDE_EFFECTS",
  "NO_UNAUDITABLE_SAVINGS_CLAIM",
  "NO_UNTRACEABLE_LOSSY_TRANSFORM",
  "NO_UNBOUNDED_ESCALATION",
  "VERIFICATION_COST_COUNTS",
  "HUMAN_ATTENTION_IS_SCARCE",
  "NEGATIVE_RESULTS_REMAIN_VISIBLE",
  "LEARNING_CANNOT_EDIT_CONSTITUTION",
  "SELF_REPORTED_MODEL_CONFIDENCE_IS_NOT_QUALIFICATION"
]);
